#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: landingzone_secure_vnet_dmz

on:
  push:
    paths:
    - 'landingzones/landingzone_secure_vnet_dmz/**'
    - 'environments/**/landingzone_secure_vnet_dmz/**'
    - '.github/workflows/ci-landingzone_secure_vnet_dmz.yml'
    branches-ignore:
        - master

env:
  TF_CLI_ARGS: '-no-color'
  TF_CLI_ARGS_destroy: '-auto-approve -refresh=false'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TF_VAR_azure_devops_pat_token: ${{ secrets.TF_VAR_azure_devops_pat_token }}
  TF_VAR_azure_devops_url_organization: ${{ secrets.TF_VAR_azure_devops_url_organization }}
  TFVARS_PATH: '/tf/caf/environments'

jobs:
  level0:
    name: level0
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
          region: ["westus2"]
          convention: ["random"]

    container:
      image: aztfmod/rover:2005.1510
      options: --user 0

    steps:
      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
      
      - name: Locate launchpad
        run: |
         id=$(az storage account list --query "[?tags.tfstate=='level0' && tags.workspace=='level0']" -o json | jq -r .[0].id)
          if [ "${id}" == "null" ]; then
            /tf/rover/launchpad.sh /tf/launchpads/launchpad_opensource plan -var location=${{ matrix.region }}
            /tf/rover/launchpad.sh /tf/launchpads/launchpad_opensource apply -var location=${{ matrix.region }}
          fi
            
  caf_foundations:
    name: caf_foundations
    runs-on: ubuntu-latest
    
    needs: level0

    strategy:
      fail-fast: false
      matrix:
          landingzone: ["landingzone_caf_foundations"]
          region: ["westus2"]
          convention: ["random"]
          environment: ["integration-tests"]

    container:
      image: aztfmod/rover:2004.1606
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name:  setup context
        id: context
        run: |
          ln -s ${GITHUB_WORKSPACE} /tf/caf
          echo "ls /tf/caf" && ls -lsa /tf/caf
          ls -lsa /tmp

          workspace='caffoundationsci'
          echo ::set-env name=TF_VAR_workspace::${workspace}

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
            
      - name: workspace      
        run: |
          /tf/rover/launchpad.sh workspace create ${TF_VAR_workspace}
  
      - name: deploy caf_foundations
        run: |
            /tf/rover/rover.sh /tf/caf/landingzones/landingzone_caf_foundations apply \
                '-var tags={testing-job-id="${{ github.run_id }}"}' \
                '-var-file ${{ env.TFVARS_PATH }}/${{ matrix.environment }}/${{ matrix.landingzone }}/${{ matrix.landingzone }}_${{ matrix.region }}_${{ matrix.convention }}.tfvars'

  landingzone_secure_vnet_dmz:
    name: landingzone_secure_vnet_dmz
    runs-on: ubuntu-latest
    
    needs: [level0, caf_foundations]

    strategy:
      fail-fast: false
      matrix:
          landingzone: ["landingzone_secure_vnet_dmz"]
          region: ["westus2"]
          convention: ["random"]
          environment: ["integration-tests"]


    container:
      image: aztfmod/rover:2005.1510
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name:  setup context
        id: context
        run: |
          ln -s ${GITHUB_WORKSPACE} /tf/caf
          echo "ls /tf/caf" && ls -lsa /tf/caf
          ls -lsa /tmp

          job_id=${{ job.container.id }}
          workspace=${job_id:0:63}
          echo ::set-env name=TF_VAR_workspace::${workspace}

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
            
      - name: workspace      
        run: |
          /tf/rover/launchpad.sh workspace create ${TF_VAR_workspace}
          

      - name: deploy secure_vnet_dmz
        run: |
          /tf/rover/rover.sh /tf/caf/landingzones/landingzone_secure_vnet_dmz apply \
            '-var tags={testing-job-id="${{ github.run_id }}"}' \
            '-var-file ${{ env.TFVARS_PATH }}/${{ matrix.environment }}/${{ matrix.landingzone }}/${{ matrix.landingzone }}.tfvars' \
            '-var workspace=caffoundationsci' 

      - name: destroy secure_vnet_dmz
        if: always()
        run: |
          /tf/rover/rover.sh /tf/caf/landingzones/landingzone_secure_vnet_dmz destroy \
            '-var tags={testing-job-id="${{ github.run_id }}"}' \
            '-var-file ${{ env.TFVARS_PATH }}/${{ matrix.environment }}/${{ matrix.landingzone }}/${{ matrix.landingzone }}.tfvars' \
            '-var workspace=caffoundationsci'

      - name: cleanup workspace
        if: always()
        run: |
          stg_name=$(az storage account list --query "[?tags.tfstate=='level0']" -o json | jq -r .[0].name)
          az storage container delete --account-name ${stg_name} --name ${TF_VAR_workspace} --auth-mode login
  
  