#
# Copyright (c) Microsoft Corporation
# Licensed under the MIT License.
#

name: landingzones

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - 'documentation/**'
      - '_pictures/**'
      - 'README.md'
      - 'CHANGELOG.md'
  schedule:
    - cron:  '0 0 * * *'

env:
  TF_CLI_ARGS: '-no-color'
  TF_CLI_ARGS_destroy: '-auto-approve -refresh=false'
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  TFVARS_PATH: '/tf/caf/caf-terraform-landingzones'

jobs:
  tfsec:
    name: Run TFsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  level0:
    name: level0
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
          region: ["westus2"]
          convention: ["random"]

    container:
      image: aztfmod/rover:2009.0210
      options: --user 0

    steps:
      - uses: actions/checkout@v2
      
      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
      
      - name: Locate launchpad
        run: |
          ln -s ${GITHUB_WORKSPACE} /tf/caf

          id=$(az storage account list --query "[?tags.tfstate=='level0' && tags.environment=='${{ github.run_id }}']" -o json | jq -r .[0].id)

          if [ "${id}" == "null" ]; then
            /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/landingzones/launchpad -a apply \
              -launchpad \
              --environment ${{ github.run_id }} \
              '-var prefix=g${{ github.run_id }}' \
              '-var location=${{ matrix.region }}' \
              '-var convention=${{ matrix.convention }}' \
              '-var tags={testing_job_id="${{ github.run_id }}"}'
          fi

  caf_foundations:
    name: caf_foundations
    runs-on: ubuntu-latest
    
    needs: level0

    strategy:
      fail-fast: false
      matrix:
          landingzone: ["landingzone_caf_foundations"]
          region: ["southeastasia"]
          convention: ["random"]
          environment: ["integration-tests"]

    container:
      image: aztfmod/rover:2009.0210
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name:  setup context
        id: context
        run: |
          ln -s ${GITHUB_WORKSPACE} /tf/caf
          echo "ls /tf/caf" && ls -lsa /tf/caf
          ls -lsa /tmp

          # workspace='caffoundationsci'
          # echo ::set-env name=TF_VAR_workspace::${workspace}

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
            
      - name: deploy caf_foundations
        run: |
            /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/landingzones/${{ matrix.landingzone }} -a apply \
              --environment ${{ github.run_id }} \
              -var prefix=g${{ github.run_id}} \
              '-var tags={testing_job_id="${{ github.run_id }}"}' \
              '-var-file ${{ env.TFVARS_PATH }}/environments/${{ matrix.environment }}/${{ matrix.landingzone }}/${{ matrix.landingzone }}_${{ matrix.region }}_${{ matrix.convention }}.tfvars' 
                
  landingzones:
    name: landingzones
    runs-on: ubuntu-latest
    
    needs: [level0, caf_foundations]

    strategy:
      fail-fast: false
      matrix:
          landingzone: ["landingzone_networking"]
          examples: ["101-multiple-vnets", "102-multiple-vnets-peering", "103-hub-vnet-with-firewall", "104-hub-vnet-with-firewall-bastion", "105-hub-virtual-wan-firewall"]
          convention: ["cafrandom"]
    
    container:
      image: aztfmod/rover:2009.0210
      options: --user 0
    
    steps:
      - uses: actions/checkout@v2

      - name:  setup context
        id: context
        run: |
          ln -s ${GITHUB_WORKSPACE} /tf/caf
          echo "ls /tf/caf" && ls -lsa /tf/caf
          ls -lsa /tmp

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
            
      - name: Deploy landing_zone
        run: |
          /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/landingzones/${{ matrix.landingzone }} -a apply \
            -env ${{ github.run_id }} \
            '-var tags={testing_job_id="${{ github.run_id }}"}' \
            -tfstate ${{ matrix.examples }}_landingzone_networking.tfstate \
            '-var-file ${{ env.TFVARS_PATH }}/landingzones/${{ matrix.landingzone }}/examples/${{ matrix.examples }}/configuration.tfvars'

      - name: Destroy landing_zone
        if: always()
        run: |
          /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/landingzones/${{ matrix.landingzone }} -a destroy \
            --environment ${{ github.run_id }} \
            '-var tags={testing_job_id="${{ github.run_id }}"}' \
            -tfstate ${{ matrix.examples }}_landingzone_networking.tfstate \
            '-var-file ${{ env.TFVARS_PATH }}/landingzones/${{ matrix.landingzone }}/examples/${{ matrix.examples }}/configuration.tfvars'
      
          
  caf_foundations_destroy:
    name: caf_foundations_destroy
    runs-on: ubuntu-latest
    if: always() 
    needs: landingzones

    strategy:
      fail-fast: false
      matrix:
          landingzone: ["landingzone_caf_foundations"]
          region: ["southeastasia"]
          convention: ["random"]
          environment: ["integration-tests"]

    container:
      image: aztfmod/rover:2009.0210
      options: --user 0

    steps:
      - uses: actions/checkout@v2

      - name:  setup context
        id: context
        run: |
          ln -s ${GITHUB_WORKSPACE} /tf/caf
          echo "ls /tf/caf" && ls -lsa /tf/caf
          ls -lsa /tmp

          # workspace='caffoundationsci'
          # echo ::set-env name=TF_VAR_workspace::${workspace}

      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
            
      - name: destroy caf_foundations
        run: |
            /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/landingzones/${{ matrix.landingzone }} -a destroy \
              --environment ${{ github.run_id }} \
              -var prefix=g${{ github.run_id}} \
              '-var tags={testing_job_id="${{ github.run_id }}"}' \
              '-var-file ${{ env.TFVARS_PATH }}/environments/${{ matrix.environment }}/${{ matrix.landingzone }}/${{ matrix.landingzone }}_${{ matrix.region }}_${{ matrix.convention }}.tfvars' \
              '-auto-approve'

  level0_destroy:
    name: level0_destroy
    runs-on: ubuntu-latest
    if: always()
    needs: caf_foundations_destroy

    strategy:
      fail-fast: false
      matrix:
          region: ["westus2"]
          convention: ["random"]

    container:
      image: aztfmod/rover:2009.0210
      options: --user 0

    steps:
      - uses: actions/checkout@v2
      
      - name: Login azure
        run: |
          az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
          az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

          echo "local user: $(whoami)"
      
      - name: Remove launchpad
        run: |
          ln -s ${GITHUB_WORKSPACE} /tf/caf

          /tf/rover/rover.sh -lz /tf/caf/caf-terraform-landingzones/landingzones/launchpad -a destroy \
            -launchpad \
            -env ${{ github.run_id }} \
            '-var prefix=g${{ github.run_id }}' \
            '-var location=${{ matrix.region }}' \
            '-var convention=${{ matrix.convention }}' \
            '-var tags={testing_job_id="${{ github.run_id }}"}' \
            -auto-approve
        
          
      - name: Complete purge
        if: ${{ always() }}
        run: |
          for i in `az monitor log-profiles list -o tsv --query '[].name'`; do az monitor log-profiles delete --name $i; done
          for i in `az ad group list --query "[?contains(displayName, '${{ github.run_id }}')].objectId" -o tsv`; do echo "purging Azure AD group: $i" && $(az ad group delete --verbose --group $i || true); done
          for i in `az ad app list --query "[?contains(displayName, '${{ github.run_id }}')].appId" -o tsv`; do echo "purging Azure AD app: $i" && $(az ad app delete --verbose --id $i || true); done
          for i in `az group list --query "[?tags.testing_job_id=='${{ github.run_id }}'].name" -o tsv`; do echo "purging resource group: $i" && $(az group delete -n $i -y --no-wait || true); done
          for i in `az role assignment list --query "[?contains(roleDefinitionName, '${{ github.run_id }}')].roleDefinitionName" -o tsv`; do echo "purging role assignment: $i" && $(az role assignment delete --role $i || true); done
          for i in `az role definition list --query "[?contains(roleName, '${{ github.run_id }}')].roleName" -o tsv`; do echo "purging custom role definition: $i" && $(az role definition delete --name $i || true); done
