# #
# # Copyright (c) Microsoft Corporation
# # Licensed under the MIT License.
# #

# name: vnext-100

# on:
#   push:
#     branches:
#       - vnext
#     paths-ignore:
#       - .github/workflows/vnext-200.yaml
#       - 'documentation/**'
#       - '_pictures/**'
#       - 'README.md'
#       - 'CHANGELOG.md'
#   schedule:
#     - cron:  '0 2 * * *'

# env:
#   TF_CLI_ARGS: '-no-color'
#   TF_CLI_ARGS_destroy: '-auto-approve -refresh=false'
#   ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
#   ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
#   ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#   ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

# jobs:
#   foundations:
#     name: foundations
#     runs-on: ubuntu-latest

#     strategy:
#       fail-fast: true
#       max-parallel: 1
#       matrix:
#           region: ["southeastasia"]

#     container:
#       image: aztfmod/roveralpha:2009.180404
#       options: --user 0

#     steps:
#       - uses: actions/checkout@v2

#       - name: Login azure
#         run: |
#           az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
#           az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

#           echo "local user: $(whoami)"

#       - name: launchpad
#         run: |
#           # ln -s ${GITHUB_WORKSPACE} /tf/caf

#           # ls /tf/caf

#           id=$(az storage account list --query "[?tags.tfstate=='level0' && tags.environment=='${{ github.run_id }}']" -o json | jq -r .[0].id)

#           if [ "${id}" == "null" ]; then

#             /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_launchpad -a apply \
#               -var-file ${GITHUB_WORKSPACE}/landingzones/caf_launchpad/scenario/100/ci-configuration.tfvars \
#               -launchpad \
#               --environment ${{ github.run_id }} \
#               '-var prefix=g${{ github.run_id }}' \
#               '-var regions={region1="${{ matrix.region }}"}' \
#               '-var tags={testing_job_id="${{ github.run_id }}"}'
#           fi

#       - name: foundations
#         run: |
#           /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_foundations -a apply \
#           --environment ${{ github.run_id }}

#       - name: networking_hub
#         run: |
#           /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_networking -a apply \
#             -tfstate networking_hub.tfstate \
#             -var-file ${GITHUB_WORKSPACE}/landingzones/caf_networking/scenario/100-single-region-hub/configuration.tfvars \
#             --environment ${{ github.run_id }}

#   examples:
#     name: examples
#     runs-on: ubuntu-latest

#     needs: foundations

#     strategy:
#       fail-fast: false
#       matrix:
#           config_files: [
#             "examples/compute/virtual_machine/100-simple-vm",
#             "examples/networking/private_dns/100-private-dns-vnet-links",
#             "examples/redis_cache/100-redis-standard",
#             "examples/webapps/appservice/101-appservice-simple",
#             "examples/webapps/appservice/102-appservice-slots",
#             "examples/webapps/appservice/103-appservice-slots",
#             "examples/webapps/appservice-environment/101-simple_ase"
#           ]

#     container:
#       image: aztfmod/roveralpha:2009.180404
#       options: --user 0

#     steps:
#       - uses: actions/checkout@v2

#       - name: Login azure
#         run: |
#           az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
#           az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

#       - name: deploy example
#         run: |
#           /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/solutions -a apply \
#             -tfstate $(basename ${{ matrix.config_files }}).tfstate \
#             -var-file ${GITHUB_WORKSPACE}/solutions/${{ matrix.config_files }}/configuration.tfvars \
#             --environment ${{ github.run_id }}

#       - name: destroy example
#         run: |
#           /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/solutions -a destroy \
#             -tfstate $(basename ${{ matrix.config_files }}).tfstate \
#             -var-file ${GITHUB_WORKSPACE}/solutions/${{ matrix.config_files }}/configuration.tfvars \
#             --environment ${{ github.run_id }} \
#             -auto-approve


#   foundations_destroy:
#     name: foundations_destroy
#     runs-on: ubuntu-latest
#     if: always()
#     needs: examples

#     strategy:
#       fail-fast: false
#       matrix:
#           region: ["southeastasia"]

#     container:
#       image: aztfmod/roveralpha:2009.180404
#       options: --user 0

#     steps:
#       - uses: actions/checkout@v2

#       - name: Login azure
#         run: |
#           az login --service-principal -u '${{ env.ARM_CLIENT_ID }}' -p '${{ env.ARM_CLIENT_SECRET }}' --tenant '${{ env.ARM_TENANT_ID }}'
#           az account set -s  ${{ env.ARM_SUBSCRIPTION_ID }}

#           echo "local user: $(whoami)"

#       - name: networking_hub
#         run: |
#           /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_networking -a destroy \
#           -var-file ${GITHUB_WORKSPACE}/landingzones/caf_networking/scenario/100-single-region-hub/configuration.tfvars \
#           --environment ${{ github.run_id }} \
#           -auto-approve


#       - name: foundations
#         run: |
#           /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_foundations -a destroy \
#           --environment ${{ github.run_id }} \
#           -auto-approve

#       - name: Remove launchpad
#         run: |

#           /tf/rover/rover.sh -lz ${GITHUB_WORKSPACE}/landingzones/caf_launchpad/ -a destroy \
#             -var-file ${GITHUB_WORKSPACE}/landingzones/caf_launchpad/scenario/100/ci-configuration.tfvars \
#             -launchpad \
#             --environment ${{ github.run_id }} \
#             '-var prefix=g${{ github.run_id }}' \
#             '-var regions={region1="${{ matrix.region }}"}' \
#             '-var tags={testing_job_id="${{ github.run_id }}"}' \
#             -auto-approve


#       - name: Complete purge
#         if: ${{ always() }}
#         run: |
#           for i in `az monitor log-profiles list -o tsv --query '[].name'`; do az monitor log-profiles delete --name $i; done
#           for i in `az ad group list --query "[?contains(displayName, '${{ github.run_id }}')].objectId" -o tsv`; do echo "purging Azure AD group: $i" && $(az ad group delete --verbose --group $i || true); done
#           for i in `az ad app list --query "[?contains(displayName, '${{ github.run_id }}')].appId" -o tsv`; do echo "purging Azure AD app: $i" && $(az ad app delete --verbose --id $i || true); done
#           for i in `az group list --query "[?tags.environment=='${{ github.run_id }}'].name" -o tsv`; do echo "purging resource group: $i" && $(az group delete -n $i -y --no-wait || true); done
#           for i in `az role assignment list --query "[?contains(roleDefinitionName, '${{ github.run_id }}')].roleDefinitionName" -o tsv`; do echo "purging role assignment: $i" && $(az role assignment delete --role $i || true); done
#           for i in `az role definition list --query "[?contains(roleName, '${{ github.run_id }}')].roleName" -o tsv`; do echo "purging custom role definition: $i" && $(az role definition delete --name $i || true); done